spring:
  application:
    name: blogplatform
  datasource:
    url: jdbc:postgresql://localhost:5433/blogplatform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    access-token-duration: 15m
    refresh-token-duration: 7d
    secret: custodian-shortness-degrease-carnivore7-transpose-pedometer
  cookie:
    access-token-name: access_token
    refresh-token-name: refresh_token
    path: /
    refresh-path: /api/v1/auth/refresh
    max-age: 7d
